import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import {Playfair_Display} from 'next/font/google'

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const playfair = Playfair_Display({
  weight: ['400','500', '600', '700', '800', '900' ],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${playfair} antialiased`}
        className={playfair.className}
      >
        {children}
      </body>
    </html>
  );
}
